mv ./Exception/SemanticError.java ./Exception/SemanticError.hs
mv ./Exception/JumpError.java ./Exception/JumpError.hs
mv ./Exception/SyntaxException.java ./Exception/SyntaxException.hs
mv ./Exception/CompileException.java ./Exception/CompileException.hs
mv ./Exception/OptionParseError.java ./Exception/OptionParseError.hs
mv ./Exception/SemanticException.java ./Exception/SemanticException.hs
mv ./Exception/IPCException.java ./Exception/IPCException.hs
mv ./Exception/FileException.java ./Exception/FileException.hs
mv ./Utils/Cursor.java ./Utils/Cursor.hs
mv ./Utils/ErrorHandler.java ./Utils/ErrorHandler.hs
mv ./Utils/ListUtils.java ./Utils/ListUtils.hs
mv ./Utils/CommandUtils.java ./Utils/CommandUtils.hs
mv ./Utils/TextUtils.java ./Utils/TextUtils.hs
mv ./Utils/AsmUtils.java ./Utils/AsmUtils.hs
mv ./Sysdep/AssemblerOptions.java ./Sysdep/AssemblerOptions.hs
mv ./Sysdep/GNULinker.java ./Sysdep/GNULinker.hs
mv ./Sysdep/Linker.java ./Sysdep/Linker.hs
mv ./Sysdep/GNUAssembler.java ./Sysdep/GNUAssembler.hs
mv ./Sysdep/Platform.java ./Sysdep/Platform.hs
mv ./Sysdep/CodeGeneratorOptions.java ./Sysdep/CodeGeneratorOptions.hs
mv ./Sysdep/X86Linux.java ./Sysdep/X86Linux.hs
mv ./Sysdep/Assembler.java ./Sysdep/Assembler.hs
mv ./Sysdep/x86/Register.java ./Sysdep/x86/Register.hs
mv ./Sysdep/x86/PeepholeOptimizer.java ./Sysdep/x86/PeepholeOptimizer.hs
mv ./Sysdep/x86/RegisterClass.java ./Sysdep/x86/RegisterClass.hs
mv ./Sysdep/x86/CodeGenerator.java ./Sysdep/x86/CodeGenerator.hs
mv ./Sysdep/x86/ELFConstants.java ./Sysdep/x86/ELFConstants.hs
mv ./Sysdep/x86/AssemblyCode.java ./Sysdep/x86/AssemblyCode.hs
mv ./Sysdep/CodeGenerator.java ./Sysdep/CodeGenerator.hs
mv ./Sysdep/LinkerOptions.java ./Sysdep/LinkerOptions.hs
mv ./Sysdep/AssemblyCode.java ./Sysdep/AssemblyCode.hs
mv ./Ast/GotoNode.java ./Ast/GotoNode.hs
mv ./Ast/CompositeTypeDefinition.java ./Ast/CompositeTypeDefinition.hs
mv ./Ast/SizeofTypeNode.java ./Ast/SizeofTypeNode.hs
mv ./Ast/LHSNode.java ./Ast/LHSNode.hs
mv ./Ast/AddressNode.java ./Ast/AddressNode.hs
mv ./Ast/BlockNode.java ./Ast/BlockNode.hs
mv ./Ast/PrefixOpNode.java ./Ast/PrefixOpNode.hs
mv ./Ast/Slot.java ./Ast/Slot.hs
mv ./Ast/Node.java ./Ast/Node.hs
mv ./Ast/Dumper.java ./Ast/Dumper.hs
mv ./Ast/WhileNode.java ./Ast/WhileNode.hs
mv ./Ast/CflatToken.java ./Ast/CflatToken.hs
mv ./Ast/Declarations.java ./Ast/Declarations.hs
mv ./Ast/ArefNode.java ./Ast/ArefNode.hs
mv ./Ast/FuncallNode.java ./Ast/FuncallNode.hs
mv ./Ast/BreakNode.java ./Ast/BreakNode.hs
mv ./Ast/CastNode.java ./Ast/CastNode.hs
mv ./Ast/ForNode.java ./Ast/ForNode.hs
mv ./Ast/TypeDefinition.java ./Ast/TypeDefinition.hs
mv ./Ast/UnaryArithmeticOpNode.java ./Ast/UnaryArithmeticOpNode.hs
mv ./Ast/PtrMemberNode.java ./Ast/PtrMemberNode.hs
mv ./Ast/ASTVisitor.java ./Ast/ASTVisitor.hs
mv ./Ast/TypeNode.java ./Ast/TypeNode.hs
mv ./Ast/CondExprNode.java ./Ast/CondExprNode.hs
mv ./Ast/Location.java ./Ast/Location.hs
mv ./Ast/LiteralNode.java ./Ast/LiteralNode.hs
mv ./Ast/Dumpable.java ./Ast/Dumpable.hs
mv ./Ast/StructNode.java ./Ast/StructNode.hs
mv ./Ast/BinaryOpNode.java ./Ast/BinaryOpNode.hs
mv ./Ast/AST.java ./Ast/AST.hs
mv ./Ast/OpAssignNode.java ./Ast/OpAssignNode.hs
mv ./Ast/LabelNode.java ./Ast/LabelNode.hs
mv ./Ast/VariableNode.java ./Ast/VariableNode.hs
mv ./Ast/ReturnNode.java ./Ast/ReturnNode.hs
mv ./Ast/StmtNode.java ./Ast/StmtNode.hs
mv ./Ast/SwitchNode.java ./Ast/SwitchNode.hs
mv ./Ast/IfNode.java ./Ast/IfNode.hs
mv ./Ast/DereferenceNode.java ./Ast/DereferenceNode.hs
mv ./Ast/SizeofExprNode.java ./Ast/SizeofExprNode.hs
mv ./Ast/TypedefNode.java ./Ast/TypedefNode.hs
mv ./Ast/MemberNode.java ./Ast/MemberNode.hs
mv ./Ast/StringLiteralNode.java ./Ast/StringLiteralNode.hs
mv ./Ast/UnionNode.java ./Ast/UnionNode.hs
mv ./Ast/ExprStmtNode.java ./Ast/ExprStmtNode.hs
mv ./Ast/UnaryOpNode.java ./Ast/UnaryOpNode.hs
mv ./Ast/ExprNode.java ./Ast/ExprNode.hs
mv ./Ast/SuffixOpNode.java ./Ast/SuffixOpNode.hs
mv ./Ast/LogicalAndNode.java ./Ast/LogicalAndNode.hs
mv ./Ast/DoWhileNode.java ./Ast/DoWhileNode.hs
mv ./Ast/LogicalOrNode.java ./Ast/LogicalOrNode.hs
mv ./Ast/ContinueNode.java ./Ast/ContinueNode.hs
mv ./Ast/DeclarationVisitor.java ./Ast/DeclarationVisitor.hs
mv ./Ast/CaseNode.java ./Ast/CaseNode.hs
mv ./Ast/AssignNode.java ./Ast/AssignNode.hs
mv ./Ast/IntegerLiteralNode.java ./Ast/IntegerLiteralNode.hs
mv ./Ast/AbstractAssignNode.java ./Ast/AbstractAssignNode.hs
mv ./Ir/Switch.java ./Ir/Switch.hs
mv ./Ir/Mem.java ./Ir/Mem.hs
mv ./Ir/ExprStmt.java ./Ir/ExprStmt.hs
mv ./Ir/Stmt.java ./Ir/Stmt.hs
mv ./Ir/Dumper.java ./Ir/Dumper.hs
mv ./Ir/Call.java ./Ir/Call.hs
mv ./Ir/Str.java ./Ir/Str.hs
mv ./Ir/IR.java ./Ir/IR.hs
mv ./Ir/CJump.java ./Ir/CJump.hs
mv ./Ir/Var.java ./Ir/Var.hs
mv ./Ir/Dumpable.java ./Ir/Dumpable.hs
mv ./Ir/Bin.java ./Ir/Bin.hs
mv ./Ir/Addr.java ./Ir/Addr.hs
mv ./Ir/LabelStmt.java ./Ir/LabelStmt.hs
mv ./Ir/Op.java ./Ir/Op.hs
mv ./Ir/Int.java ./Ir/Int.hs
mv ./Ir/Return.java ./Ir/Return.hs
mv ./Ir/Uni.java ./Ir/Uni.hs
mv ./Ir/Expr.java ./Ir/Expr.hs
mv ./Ir/Assign.java ./Ir/Assign.hs
mv ./Ir/Jump.java ./Ir/Jump.hs
mv ./Ir/Case.java ./Ir/Case.hs
mv ./Ir/IRVisitor.java ./Ir/IRVisitor.hs
mv ./type/ArrayType.java ./type/ArrayType.hs
mv ./type/FunctionTypeRef.java ./type/FunctionTypeRef.hs
mv ./type/Type.java ./type/Type.hs
mv ./type/StructTypeRef.java ./type/StructTypeRef.hs
mv ./type/UserTypeRef.java ./type/UserTypeRef.hs
mv ./type/IntegerTypeRef.java ./type/IntegerTypeRef.hs
mv ./type/IntegerType.java ./type/IntegerType.hs
mv ./type/ArrayTypeRef.java ./type/ArrayTypeRef.hs
mv ./type/TypeTable.java ./type/TypeTable.hs
mv ./type/UserType.java ./type/UserType.hs
mv ./type/CompositeType.java ./type/CompositeType.hs
mv ./type/NamedType.java ./type/NamedType.hs
mv ./type/VoidType.java ./type/VoidType.hs
mv ./type/UnionTypeRef.java ./type/UnionTypeRef.hs
mv ./type/ParamTypes.java ./type/ParamTypes.hs
mv ./type/TypeRef.java ./type/TypeRef.hs
mv ./type/PointerType.java ./type/PointerType.hs
mv ./type/VoidTypeRef.java ./type/VoidTypeRef.hs
mv ./type/FunctionType.java ./type/FunctionType.hs
mv ./type/StructType.java ./type/StructType.hs
mv ./type/ParamTypeRefs.java ./type/ParamTypeRefs.hs
mv ./type/UnionType.java ./type/UnionType.hs
mv ./type/PointerTypeRef.java ./type/PointerTypeRef.hs
mv ./Entity/Variable.java ./Entity/Variable.hs
mv ./Entity/DefinedFunction.java ./Entity/DefinedFunction.hs
mv ./Entity/Scope.java ./Entity/Scope.hs
mv ./Entity/EntityVisitor.java ./Entity/EntityVisitor.hs
mv ./Entity/ConstantTable.java ./Entity/ConstantTable.hs
mv ./Entity/Entity.java ./Entity/Entity.hs
mv ./Entity/Parameter.java ./Entity/Parameter.hs
mv ./Entity/UndefinedFunction.java ./Entity/UndefinedFunction.hs
mv ./Entity/Function.java ./Entity/Function.hs
mv ./Entity/Params.java ./Entity/Params.hs
mv ./Entity/ConstantEntry.java ./Entity/ConstantEntry.hs
mv ./Entity/DefinedVariable.java ./Entity/DefinedVariable.hs
mv ./Entity/Constant.java ./Entity/Constant.hs
mv ./Entity/ToplevelScope.java ./Entity/ToplevelScope.hs
mv ./Entity/UndefinedVariable.java ./Entity/UndefinedVariable.hs
mv ./Entity/LocalScope.java ./Entity/LocalScope.hs
mv ./Entity/ParamSlots.java ./Entity/ParamSlots.hs
mv ./Parser/Parser.java ./Parser/Parser.hs
mv ./Parser/ParseException.java ./Parser/ParseException.hs
mv ./Parser/ParserConstants.java ./Parser/ParserConstants.hs
mv ./Parser/Token.java ./Parser/Token.hs
mv ./Parser/TokenMgrError.java ./Parser/TokenMgrError.hs
mv ./Parser/LibraryLoader.java ./Parser/LibraryLoader.hs
mv ./Parser/ParserTokenManager.java ./Parser/ParserTokenManager.hs
mv ./Parser/SimpleCharStream.java ./Parser/SimpleCharStream.hs
mv ./Compiler/Options.java ./Compiler/Options.hs
mv ./Compiler/SourceFile.java ./Compiler/SourceFile.hs
mv ./Compiler/Visitor.java ./Compiler/Visitor.hs
mv ./Compiler/LdArg.java ./Compiler/LdArg.hs
mv ./Compiler/TypeChecker.java ./Compiler/TypeChecker.hs
mv ./Compiler/LocalResolver.java ./Compiler/LocalResolver.hs
mv ./Compiler/CompilerMode.java ./Compiler/CompilerMode.hs
mv ./Compiler/LdOption.java ./Compiler/LdOption.hs
mv ./Compiler/TypeResolver.java ./Compiler/TypeResolver.hs
mv ./Compiler/Compiler.java ./Compiler/Compiler.hs
mv ./Compiler/DereferenceChecker.java ./Compiler/DereferenceChecker.hs
mv ./Compiler/IRGenerator.java ./Compiler/IRGenerator.hs
mv ./Asm/Type.java ./Asm/Type.hs
mv ./Asm/MemoryReference.java ./Asm/MemoryReference.hs
mv ./Asm/IndirectMemoryReference.java ./Asm/IndirectMemoryReference.hs
mv ./Asm/Register.java ./Asm/Register.hs
mv ./Asm/DirectMemoryReference.java ./Asm/DirectMemoryReference.hs
mv ./Asm/Statistics.java ./Asm/Statistics.hs
mv ./Asm/NamedSymbol.java ./Asm/NamedSymbol.hs
mv ./Asm/Symbol.java ./Asm/Symbol.hs
mv ./Asm/Directive.java ./Asm/Directive.hs
mv ./Asm/Literal.java ./Asm/Literal.hs
mv ./Asm/UnnamedSymbol.java ./Asm/UnnamedSymbol.hs
mv ./Asm/Instruction.java ./Asm/Instruction.hs
mv ./Asm/AbsoluteAddress.java ./Asm/AbsoluteAddress.hs
mv ./Asm/ImmediateValue.java ./Asm/ImmediateValue.hs
mv ./Asm/IntegerLiteral.java ./Asm/IntegerLiteral.hs
mv ./Asm/Label.java ./Asm/Label.hs
mv ./Asm/BaseSymbol.java ./Asm/BaseSymbol.hs
mv ./Asm/SuffixedSymbol.java ./Asm/SuffixedSymbol.hs
mv ./Asm/SymbolTable.java ./Asm/SymbolTable.hs
mv ./Asm/Comment.java ./Asm/Comment.hs
mv ./Asm/Operand.java ./Asm/Operand.hs
mv ./Asm/OperandPattern.java ./Asm/OperandPattern.hs
mv ./Asm/Assembly.java ./Asm/Assembly.hs
