module Main where
import Cflat.Parser.Parser
import Cflat.Type.Type
import Test.HUnit
import Control.Monad.State
import Control.Exception
import System.Directory
import System.Environment
main = do
    getProgName >>= print
    runTestTT test_parse_file
    -- runTestTT test_string'

test_string' = "unit test string'" ~: test [ 
                                  "1" ~: "normal" ~: parser string' "\"aaa\"" ~?= Just (STRING "!aaa","")
                                  ,"2" ~: "escape" ~: parser string' "\"a\\\"aa\"" ~?= Just (STRING "!a\\\"aa","")
                                  ,"3" ~: "split" ~: parser string' "\"a\"aa\"" ~?= Just (STRING "a","!aa\"")
                                  ,"4" ~: "Nothing" ~: parser string' "aaa" ~?= Nothing
                                  ,"5" ~: "not ended" ~: parser string' "\"aaa" ~?= Nothing
                                  ,"6" ~: "not started" ~: parser string' "aaa\"" ~?= Nothing
                                 ]
parse_file file = (do
  ret <- parseFile file
  return $ case ret of
    Nothing -> False
    _           -> True) @? file
test_parse_file = "parse from file" ~: test [ 
                                 "add" ~:  parse_file "../test/add.cb"
                                 ,"addressof" ~:  parse_file "../test/addressof.cb"
                                 ,"alloca" ~: parse_file "../test/alloca.cb"
                                 ,"alloca2" ~: parse_file "../test/alloca2.cb"
                                 ,"aref-semcheck" ~: parse_file "../test/aref-semcheck.cb"
                                 ,"aref-semcheck2" ~: parse_file "../test/aref-semcheck2.cb"
                                 ,"array-semcheck1" ~: parse_file "../test/array-semcheck1.cb"
                                 ,"array" ~: parse_file "../test/array.cb"
                                 ,"array2" ~: parse_file "../test/array2.cb"
                                 ,"assign" ~: parse_file "../test/assign.cb"
                                 ,"assoc" ~: parse_file "../test/assoc.cb"
                                 ,"bitand" ~: parse_file "../test/bitand.cb"
                                 ,"bitnot" ~: parse_file "../test/bitnot.cb"
                                 ,"bitor" ~: parse_file "../test/bitor.cb"
                                 ,"bitxor" ~: parse_file "../test/bitxor.cb"
                                 ,"block" ~: parse_file "../test/block.cb"
                                 ,"break-semcheck" ~: parse_file "../test/break-semcheck.cb"
                                 ,"cast" ~: parse_file "../test/cast.cb"
                                 ,"cast2" ~: parse_file "../test/cast2.cb"
                                 ,"charops" ~: parse_file "../test/charops.cb"
                                 ,"charops2" ~: parse_file "../test/charops2.cb"
                                 ,"comm" ~: parse_file "../test/comm.cb"
                                 ,"condexpr" ~: parse_file "../test/condexpr.cb"
                                 ,"const" ~: parse_file "../test/const.cb"
                                 ,"continue-semcheck" ~: parse_file "../test/continue-semcheck.cb"
                                 ,"dec" ~: parse_file "../test/dec.cb"
                                 ,"decloverride" ~: parse_file "../test/decloverride.cb"
                                 ,"decloverride2" ~: parse_file "../test/decloverride2.cb"
                                 ,"defun-semcheck" ~: parse_file "../test/defun-semcheck.cb"
                                 ,"defun-semcheck2" ~: parse_file "../test/defun-semcheck2.cb"
                                 ,"defun-semcheck3" ~: parse_file "../test/defun-semcheck3.cb"
                                 ,"defun-semcheck4" ~: parse_file "../test/defun-semcheck4.cb"
                                 ,"defun-semcheck5" ~: parse_file "../test/defun-semcheck5.cb"
                                 ,"defun-semcheck6" ~: parse_file "../test/defun-semcheck6.cb"
                                 ,"defun-semcheck7" ~: parse_file "../test/defun-semcheck7.cb"
                                 ,"defun-semcheck8" ~: parse_file "../test/defun-semcheck8.cb"
                                 ,"defvar" ~: parse_file "../test/defvar.cb"
                                 ,"deref-semcheck1" ~: parse_file "../test/deref-semcheck1.cb"
                                 ,"deref-semcheck2" ~: parse_file "../test/deref-semcheck2.cb"
                                 ,"deref-semcheck3" ~: parse_file "../test/deref-semcheck3.cb"
                                 ,"deref-semcheck4" ~: parse_file "../test/deref-semcheck4.cb"
                                 ,"deref-semcheck5" ~: parse_file "../test/deref-semcheck5.cb"
                                 ,"div" ~: parse_file "../test/div.cb"
                                 ,"dowhile-break" ~: parse_file "../test/dowhile-break.cb"
                                 ,"dowhile-continue" ~: parse_file "../test/dowhile-continue.cb"
                                 ,"dowhile1" ~: parse_file "../test/dowhile1.cb"
                                 ,"dowhile2" ~: parse_file "../test/dowhile2.cb"
                                 ,"dowhile3" ~: parse_file "../test/dowhile3.cb"
                                 ,"duplicated-import" ~: parse_file "../test/duplicated-import.cb"
                                 ,"empstruct" ~: parse_file "../test/empstruct.cb"
                                 ,"eq" ~: parse_file "../test/eq.cb"
                                 ,"for-break" ~: parse_file "../test/for-break.cb"
                                 ,"for-continue" ~: parse_file "../test/for-continue.cb"
                                 ,"for1" ~: parse_file "../test/for1.cb"
                                 ,"fork" ~: parse_file "../test/fork.cb"
                                 ,"funcall-semcheck" ~: parse_file "../test/funcall-semcheck.cb"
                                 ,"funcall-semcheck2" ~: parse_file "../test/funcall-semcheck2.cb"
                                 ,"funcall0" ~: parse_file "../test/funcall0.cb"
                                 ,"funcall1" ~: parse_file "../test/funcall1.cb"
                                 ,"funcall2" ~: parse_file "../test/funcall2.cb"
                                 ,"funcall3" ~: parse_file "../test/funcall3.cb"
                                 ,"funcall4" ~: parse_file "../test/funcall4.cb"
                                 ,"funcall5" ~: parse_file "../test/funcall5.cb"
                                 ,"funcptr" ~: parse_file "../test/funcptr.cb"
                                 ,"gt" ~: parse_file "../test/gt.cb"
                                 ,"gteq" ~: parse_file "../test/gteq.cb"
                                 ,"gvar" ~: parse_file "../test/gvar.cb"
                                 ,"hello" ~: parse_file "../test/hello.cb"
                                 ,"hello2" ~: parse_file "../test/hello2.cb"
                                 ,"hello3" ~: parse_file "../test/hello3.cb"
                                 ,"hello4" ~: parse_file "../test/hello4.cb"
                                 ,"if1" ~: parse_file "../test/if1.cb"
                                 ,"if2" ~: parse_file "../test/if2.cb"
                                 ,"implicitaddr" ~: parse_file "../test/implicitaddr.cb"
                                 ,"inc" ~: parse_file "../test/inc.cb"
                                 ,"initializer" ~: parse_file "../test/initializer.cb"
                                 ,"integer" ~: parse_file "../test/integer.cb"
                                 ,"intops" ~: parse_file "../test/intops.cb"
                                 ,"invalidstmt1" ~: parse_file "../test/invalidstmt1.cb"
                                 ,"invalidstmt2" ~: parse_file "../test/invalidstmt2.cb"
                                 ,"logicaland" ~: parse_file "../test/logicaland.cb"
                                 ,"logicalnot" ~: parse_file "../test/logicalnot.cb"
                                 ,"logicalor" ~: parse_file "../test/logicalor.cb"
                                 ,"longops" ~: parse_file "../test/longops.cb"
                                 ,"lshift" ~: parse_file "../test/lshift.cb"
                                 ,"lt" ~: parse_file "../test/lt.cb"
                                 ,"lteq" ~: parse_file "../test/lteq.cb"
                                 ,"lvar1" ~: parse_file "../test/lvar1.cb"
                                 ,"lvar2" ~: parse_file "../test/lvar2.cb"
                                 ,"mdarray" ~: parse_file "../test/mdarray.cb"
                                 ,"mdarray2" ~: parse_file "../test/mdarray2.cb"
                                 ,"mod" ~: parse_file "../test/mod.cb"
                                 ,"mul" ~: parse_file "../test/mul.cb"
                                 ,"neq" ~: parse_file "../test/neq.cb"
                                 ,"noreturn" ~: parse_file "../test/noreturn.cb"
                                 ,"one" ~: parse_file "../test/one.cb"
                                 ,"opassign" ~: parse_file "../test/opassign.cb"
                                 ,"param" ~: parse_file "../test/param.cb"
                                 ,"pointer" ~: parse_file "../test/pointer.cb"
                                 ,"pointer2" ~: parse_file "../test/pointer2.cb"
                                 ,"pointer3" ~: parse_file "../test/pointer3.cb"
                                 ,"pointer4" ~: parse_file "../test/pointer4.cb"
                                 ,"ptrarray" ~: parse_file "../test/ptrarray.cb"
                                 ,"ptrdiff" ~: parse_file "../test/ptrdiff.cb"
                                 ,"ptrmemb" ~: parse_file "../test/ptrmemb.cb"
                                 ,"ptrmemb2" ~: parse_file "../test/ptrmemb2.cb"
                                 ,"recursivetypedef" ~: parse_file "../test/recursivetypedef.cb"
                                 ,"rshift" ~: parse_file "../test/rshift.cb"
                                 ,"scomm" ~: parse_file "../test/scomm.cb"
                                 ,"setjmptest" ~: parse_file "../test/setjmptest.cb"
                                 ,"sgvar" ~: parse_file "../test/sgvar.cb"
                                 ,"shortops" ~: parse_file "../test/shortops.cb"
                                 ,"shortops2" ~: parse_file "../test/shortops2.cb"
                                 ,"sizeof-expr" ~: parse_file "../test/sizeof-expr.cb"
                                 ,"sizeof-struct" ~: parse_file "../test/sizeof-struct.cb"
                                 ,"sizeof-type" ~: parse_file "../test/sizeof-type.cb"
                                 ,"sizeof-union" ~: parse_file "../test/sizeof-union.cb"
                                 ,"slcomm" ~: parse_file "../test/slcomm.cb"
                                 ,"slvar" ~: parse_file "../test/slvar.cb"
                                 ,"src1" ~: parse_file "../test/src1.cb"
                                 ,"src2" ~: parse_file "../test/src2.cb"
                                 ,"staticfunc" ~: parse_file "../test/staticfunc.cb"
                                 ,"string" ~: parse_file "../test/string.cb"
                                 ,"struct-semcheck" ~: parse_file "../test/struct-semcheck.cb"
                                 ,"struct-semcheck10" ~: parse_file "../test/struct-semcheck10.cb"
                                 ,"struct-semcheck2" ~: parse_file "../test/struct-semcheck2.cb"
                                 ,"struct-semcheck3" ~: parse_file "../test/struct-semcheck3.cb"
                                 ,"struct-semcheck4" ~: parse_file "../test/struct-semcheck4.cb"
                                 ,"struct-semcheck5" ~: parse_file "../test/struct-semcheck5.cb"
                                 ,"struct-semcheck6" ~: parse_file "../test/struct-semcheck6.cb"
                                 ,"struct-semcheck7" ~: parse_file "../test/struct-semcheck7.cb"
                                 ,"struct-semcheck8" ~: parse_file "../test/struct-semcheck8.cb"
                                 ,"struct-semcheck9" ~: parse_file "../test/struct-semcheck9.cb"
                                 ,"struct" ~: parse_file "../test/struct.cb"
                                 ,"struct2" ~: parse_file "../test/struct2.cb"
                                 ,"struct3" ~: parse_file "../test/struct3.cb"
                                 ,"sub" ~: parse_file "../test/sub.cb"
                                 ,"switch" ~: parse_file "../test/switch.cb"
                                 ,"syntax1" ~: parse_file "../test/syntax1.cb"
                                 ,"syntax2" ~: parse_file "../test/syntax2.cb"
                                 ,"syntax3" ~: parse_file "../test/syntax3.cb"
                                 ,"textwrite" ~: parse_file "../test/textwrite.cb"
                                 ,"ucharops" ~: parse_file "../test/ucharops.cb"
                                 ,"ucharops2" ~: parse_file "../test/ucharops2.cb"
                                 ,"uintops" ~: parse_file "../test/uintops.cb"
                                 ,"ulongops" ~: parse_file "../test/ulongops.cb"
                                 ,"unaryminus" ~: parse_file "../test/unaryminus.cb"
                                 ,"unaryplus" ~: parse_file "../test/unaryplus.cb"
                                 ,"union-semcheck" ~: parse_file "../test/union-semcheck.cb"
                                 ,"union-semcheck10" ~: parse_file "../test/union-semcheck10.cb"
                                 ,"union-semcheck2" ~: parse_file "../test/union-semcheck2.cb"
                                 ,"union-semcheck3" ~: parse_file "../test/union-semcheck3.cb"
                                 ,"union-semcheck4" ~: parse_file "../test/union-semcheck4.cb"
                                 ,"union-semcheck5" ~: parse_file "../test/union-semcheck5.cb"
                                 ,"union-semcheck6" ~: parse_file "../test/union-semcheck6.cb"
                                 ,"union-semcheck7" ~: parse_file "../test/union-semcheck7.cb"
                                 ,"union-semcheck8" ~: parse_file "../test/union-semcheck8.cb"
                                 ,"union-semcheck9" ~: parse_file "../test/union-semcheck9.cb"
                                 ,"union" ~: parse_file "../test/union.cb"
                                 ,"usertype" ~: parse_file "../test/usertype.cb"
                                 ,"ushortops" ~: parse_file "../test/ushortops.cb"
                                 ,"ushortops2" ~: parse_file "../test/ushortops2.cb"
                                 ,"utf" ~: parse_file "../test/utf.cb"
                                 ,"validstmt1" ~: parse_file "../test/validstmt1.cb"
                                 ,"var-semcheck" ~: parse_file "../test/var-semcheck.cb"
                                 ,"varargs" ~: parse_file "../test/varargs.cb"
                                 ,"vardecl" ~: parse_file "../test/vardecl.cb"
                                 ,"while-break" ~: parse_file "../test/while-break.cb"
                                 ,"while-continue" ~: parse_file "../test/while-continue.cb"
                                 ,"while1" ~: parse_file "../test/while1.cb"
                                 ,"while2" ~: parse_file "../test/while2.cb"
                                 ,"while3" ~: parse_file "../test/while3.cb"
                                 ,"zero" ~: parse_file "../test/zero.cb"
                                 ,"addressof" ~:  parse_file "../test/addressof.cb"
                                 ]
createEmptyFile file = writeFile file "this is temp file"
testIO = "createEmptyFile" ~:
         (do 
           (bracket
             (return ())
             -- (\dmy  -> return ())
             (\dmy  -> removeFile file)
             (\dmy' -> (do
                 (doesFileExist file >>= return . not) @? "Pre-condition test: File already exist."
                 createEmptyFile file
                 exi <- doesFileExist file
                 exi @? "file is not exists."
                 txt <- readFile file
                 txt @=? "this is temp file")))
           (doesFileExist file >>= \ret -> return . not $ ret) @? "Post-condition test: file is not removed.")
       where file = "sample.txt"

